### PR TITLE
Stack using Queue

### PR DESCRIPTION
**Pull request by Faizan96322**

### CODE REVIEW

**Comment by Kanai2003** [comment]
while pushing, some errors found
please correct it

**Comment by Faizan96322** [comment]
> while pushing, some errors found
> please correct it

can you please specify the error!

**Comment by Faizan96322** [comment]
Screenshot 2022-10-05 at 1 04 08 PM
this is the screenshot of my output!

**Comment by Kanai2003** [comment]
` queue_display() ` func. is printing some garbage value

**Comment by Kanai2003** [comment]
@Faizan96322 what's the current status?

**Pull request closed without merging**
